global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Loan API metrics
  - job_name: 'loan-api'
    static_configs:
      - targets: ['loan-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Nginx metrics (if nginx_prometheus_exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
