version: '3.8'

services:
  # Loan Onboarding API
  loan-api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_DATE: "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        VCS_REF: "$(git rev-parse --short HEAD)"
        VERSION: "${VERSION:-latest}"
    container_name: loan-onboarding-api
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - ENV=${ENV:-development}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env

    volumes:
      - ../logs:/app/logs
    networks:
      - loan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: loan-nginx
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - loan-api
    networks:
      - loan-network
    restart: unless-stopped

volumes:

networks:
  loan-network:
    driver: bridge
