version: '3.8'

services:
  # Loan Onboarding API
  loan-api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_DATE: "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        VCS_REF: "$(git rev-parse --short HEAD)"
        VERSION: "${VERSION:-latest}"
    container_name: loan-onboarding-api
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - ENV=${ENV:-development}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - USE_MOCK_AWS=true
    env_file:
      - .env
    volumes:
      - ../logs:/app/logs
    networks:
      - loan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Prometheus for monitoring (optional for local development)
  prometheus:
    image: prom/prometheus:latest
    container_name: loan-prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - loan-network
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    profiles:
      - monitoring

volumes:
  prometheus_data:

networks:
  loan-network:
    driver: bridge
